algorithms:
  ajtai: false
  angluin: true
  margulis: true
  random_3: true
  random_5: true
params:
  c: 1000
  cleanup: true
  clear_results_files: true
  epsilon: 1.0e-06
  n: 30
  output_indices_matrices: false
  output_initializer_matrices: false
  random_graphs_samples: 50
