expanders:
  n:                            4
  cleanup:                      True
  output_initializer_matrices:  True
  angluin_method:               True
  margulis_method:              True
  random_3:                     False
  random_5:                     False