expanders:
  angluin_method: true
  cleanup: true
  clear_results_files: false
  margulis_method: false
  n: 100
  output_expander_adjacency: false
  output_indices_matrices: false
  output_initializer_matrices: false
  random_3: false
  random_5: false
