expanders:
  n:                            2
  cleanup:                      True
  output_indices_matrices:      False
  output_initializer_matrices:  False
  output_expander_adjacency:    False
  output_eigenvalues:           False
  angluin_method:               True
  margulis_method:              True
  random_3:                     False
  random_5:                     False