algorithms:
  angluin_method: false
  margulis_method: false
  random_3: true
  random_5: true
params:
  cleanup: true
  clear_results_files: false
  epsilon: 1.0e-06
  n: 10
  random_graphs_samples: 1000
  output_indices_matrices: false
  output_initializer_matrices: false
